inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from:
  - .rubocop_todo.yml

require: rubocop-performance

Performance:
  Enabled: true

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'vendor/bundle/**/*'
